language: python
python:
- '2.7'
- '3.5'
- '3.6'
install: pip install pyflakes==1.5.0
script: pyflakes beeline && python setup.py test
deploy:
  provider: pypi
  user: honeycomb
  on:
    tags: true
    repo: honeycombio/beeline-python
  password:
    secure: BstULKsJO1uJ3Q+wI1ox0St79sFiS7nzpOzrapdSpi4H/TBRI+yiyzL/vVrDKz0Xh42Krn3Ht9dpAR07VjneolTtkwL6ZFrrEiSyA9QVnJUqHQooBjJaEFpZN2gaffQ1y6bAXqI1jYm8OUxQRoKdpEQLudpJdGDuMju2bhUygfzKMl6VO0132w09oPresfcoRlalHgDhGVqYAu4SV7PvEfndvRGXyTiRjWuWbPkFOtFkSf3UsiF3spZf7Xskyfs4N2QR+FnfK62RMby0ZYkJ9yxXQkTOkJ4BR4zud01rPPue0opa1LhkPAoqWUJUyYNs+2r4kJwPHzb8yf1TJDNDpQs/PdOL7ss0MrRRl/k7Acg8kEqwxUhPNfRVlcNs4uOyuuhuGAMDtIRLQ11y4yYTW1aOMgbjUExJqMLixeoDQgjBN7LhY+HZrMYZLHCkI3IPha8gfKNWAqyuoLjWcFzWAAEWjYSNxE3ruaUxxhMsLPXfOmH6NZj+IIgVbFU85glYa3sbGAuEH5UCKYebRdzw2ZNyHhrGIqgmQyLZg6YHCw58rn//94F9EP0XR9sWkh2rlLDz8wy/ThUtTZPHhLzzvR2gmASalmOjfYfR4Kxrtz22UX2mp5da8eJdZy/cue1gh5kFQuW3q6LllqWLqn9CRNjlNoPzTLHPaAFGEoQ45oA=
