sudo: required
dist: trusty
language: php
php:
  - 7.1
  - 7.2
  - 7.3

env:
  global:
  - SERVER_BRANCH=master
  - PHP_COVERAGE=FALSE
  matrix:
  - DB=sqlite

branches:
  only:
  - master
  - "/^stable\\d+(\\.\\d+)?$/"
  - /^v\d++(\.\d+)?+(\.\d+)?+(\.\d+)?$/

cache:
  directories:
  - "$HOME/.composer/cache/files"
  - "$HOME/.npm"
  - "$HOME/.cache/bower"

before_install:
  # XDebug is only needed if we report coverage -> speeds up other builds (7.3 has no xdebug yet)
  - if [[ "$PHP_COVERAGE" = "FALSE" ]]; then phpenv config-rm xdebug.ini || true; fi

  - composer self-update
  - composer install
  - cd ..
  - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $SERVER_BRANCH core
  - mv twofactor_gateway core/apps/

before_script:
  # Set up core
  - php -f core/occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''

  # Set up app
  - php -f core/occ app:enable twofactor_gateway

  - cd core/apps/twofactor_gateway

script:
  # Check PHP syntax errors
  - find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;

  # Run server's app code checker
  - php ../../occ app:check-code twofactor_gateway

  # Run PHP tests
  - ./vendor/bin/phpunit --fail-on-warning -c tests/phpunit.xml
  - ./vendor/bin/phpunit --fail-on-warning -c tests/phpunit.integration.xml

after_script:
  # Upload coverage report to Scrutinizer
  - if [[ "$PHP_COVERAGE" = "TRUE" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$PHP_COVERAGE" = "TRUE" ]]; then php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml; fi

matrix:
  include:
    - php: 7.2
      env: "DB=sqlite SERVER_BRANCH=v16.0.0"
    - php: 7.3
      env: "DB=sqlite SERVER_BRANCH=stable16"
    - php: 7.3
      env: "DB=sqlite SERVER_BRANCH=stable17"
    - php: 7.3
      env: "DB=sqlite"
    - php: 7.2
      env: "DB=sqlite PHP_COVERAGE=TRUE"
  fast_finish: true
