language: python
python:
- '2.7'
- '3.5'
- '3.6'
install: pip install pyflakes==1.5.0
script: pyflakes beeline && python setup.py test
deploy:
  provider: pypi
  user: honeycomb
  on:
    tags: true
    repo: honeycombio/beeline-python
  password:
    secure: D4jIl+eGxrgsuucnsg2ft6TkEwj+yrYZWR+BD1GnJg/9kCSka47dOKZ8jxWkwny0DyT4LA9cck55FzWKjaVdW4KuANS9P6D0WpiBYp6bbAdY42cAR8DMuEj2xoTzhVfy+RhmFUyQeb70gavXZfpCnHREJRx4na8Xwkpwv5mxXVxL7cv0OEWpv0naGc2e9GO42GDbJ86GAoor/OBdxy5Ca2RlkIiKYOGjfcfxqSldx36JsnaaXAeuYzm2Cs7QYVI6b66Wp+OHMMJoFvmjlVLx4DhzW7bYurPos5xNDzug1i8YDTjjRWPZU6BzmCkbdlrGoBi6V72uzPUzXzGIRq/DViCQgBQtyAQjE38MlKIyONbqjz5sAR7gALa/yd8ZeTn5db0NGDeV8loC9gGWSU0jC6c7GN8/KHbBK6TiL/6YzfJw6OdvlT97xN0WxcGOzw1z6RhuEJi3Yx59oxvKXvRodTIXiTTzq6TufWqT79A09PcyYqoZW9DWg/utf9SuXg1L81sGR+CfgroAlRXbpQx6lTVFbLtd4y5SoLC1zNh5VVMPxNCOnFjp6F3Jttu5U/YK6kV6me4OmVo+5OoBb6qEPHJkRAFCspI06gs4s6qqJNmlsD9fKsITFnfagQwAQ+CyYim/PAva22UqeAvJdd3tmZgALwymnFeD4C2vz87bIpk=
