language: python
python:
- '2.7'
- '3.5'
- '3.6'
install: pip install pyflakes==1.5.0
script: pyflakes beeline && python setup.py test
deploy:
  provider: pypi
  user: honeycomb
  on:
    tags: true
    repo: honeycombio/beeline-python
  password:
    secure: ud5fOqhPFFAgRYyIdsrXq4Sn9D1BKBxOd7jFT4+XicPqGh6682NV3HJadnh9bqPDBZuF2xOtt3XQ/riw1lvWz3QooSm0MYt6o2Ao5Gcn+Lc9/atNCdYu3WCGZGWAWTD148tBbS5B+uAnbAr6XQFqtAklT5HL4PhG2FlrVBL2R0AVS5CtZC+38fSz/WSyg86pRgWFaYYRdizd4UMqPe3D6wd6oeW6A7ejfkyvWHDZBNbHCmEqo0a1rMLh6stpHup7/xZ3U+Vx+dHnTvVusJpWJDn4E4N6zQU3zRRClwnyTfjeLN+37SoWEd8rwMDzkuglL6XaDPQRdEX15W7AVPD0uADJsfOFIWCVHOESFo7v4akLfXH8Ig/krPKbDxDOUwUCWqv6bfztqpVWWc6ZT57sNM6ixvsBxVKmNWWn9BXW2H+6pv/orCD7tYDg/mrSsLI3SbGB7CClTXyaJg2KImvNNVCv6l4rM6gJh5jhsZhJ04yi1+PzVI32boVgY53DA3MkerA0ePOtW37f4XDsmslmpRoZpE2J6CXPOpKdqxTkbjXAq0O+KnjcnXnx3rdVxwyAUgLaWvlmlwXtff51+Vi+wMbS3EX9qRQmb35V8gpxh6zhJ9OPzh3kcH78QWb0rgTa8IPnqDqJWII/4ugHJf5MDfuBCmx/djpMp86n3q6euDE=
