[package]
name = "ensight"
version = "0.1.0"
authors = ["yasuyuky <yasuyuki.ymd@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = "1.0.152"
serde_json = "1.0.91"
surf = "2.0.0"
colored = "2.0.0"
toml = "0.7.1"
once_cell = "1.17.0"
colorgrad = "0.6.2"
either = { version = "1.8.1", features = ["serde"] }
serde_yaml = "0.9.17"
anyhow = "1.0.68"
base64 = "0.21.0"
time = { version = "0.3.17", features = ["serde", "serde-well-known"] }
clap = { version = "4.1.4", features = ["derive"] }

[dependencies.async-std]
features = ["attributes"]
version = "1.12.0"
