[package]
name = "ensight"
version = "0.1.0"
authors = ["yasuyuky <yasuyuki.ymd@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = "1.0.159"
serde_json = "1.0.95"
surf = "2.0.0"
colored = "2.0.0"
toml = "0.7.3"
once_cell = "1.17.1"
colorgrad = "0.6.2"
either = { version = "1.8.1", features = ["serde"] }
serde_yaml = "0.9.19"
anyhow = "1.0.70"
base64 = "0.21.0"
time = { version = "0.3.20", features = ["serde", "serde-well-known"] }
clap = { version = "4.1.11", features = ["derive"] }

[dependencies.async-std]
features = ["attributes"]
version = "1.12.0"
