[package]
name = "ensight"
version = "0.1.0"
authors = ["yasuyuky <yasuyuki.ymd@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = "1.0.137"
serde_json = "1.0.81"
structopt = "0.3.26"
surf = "2.0.0"
colored = "2.0.0"
toml = "0.5.9"
once_cell = "1.11.0"
chrono = { version = "0.4.19", features = ["serde"] }
colorgrad = "0.5.0"
either = { version = "1.6.1", features = ["serde"] }
serde_yaml = "0.8.24"
anyhow = "1.0.57"
base64 = "0.13.0"
ansi_term = "0.12.1"

[dependencies.async-std]
features = ["attributes"]
version = "1.11.0"
