[package]
name = "sovereign-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.1"
sha2 = "0.10.6"
jmt = { git  = "https://github.com/penumbra-zone/jmt.git", rev = "18eb03cf053d15799ee3aa0c09b56c9f44485175" }
