[package]
name = "ensight"
version = "0.1.0"
authors = ["yasuyuky <yasuyuki.ymd@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = "1.0.143"
serde_json = "1.0.83"
structopt = "0.3.26"
surf = "2.0.0"
colored = "2.0.0"
toml = "0.5.9"
once_cell = "1.13.0"
colorgrad = "0.6.1"
either = { version = "1.7.0", features = ["serde"] }
serde_yaml = "0.9.9"
anyhow = "1.0.62"
base64 = "0.13.0"
ansi_term = "0.12.1"
time = { version = "0.3.13", features = ["serde", "serde-well-known"] }

[dependencies.async-std]
features = ["attributes"]
version = "1.12.0"
