[package]
name = "ensight"
version = "0.1.0"
authors = ["yasuyuky <yasuyuki.ymd@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = "1.0.206"
serde_json = "1.0.124"
surf = "2.0.0"
colored = "2.1.0"
once_cell = "1.19.0"
colorgrad = "0.7.0"
anyhow = "1.0.86"
base64 = "0.22.1"
time = { version = "0.3.36", features = ["serde", "serde-well-known"] }
clap = { version = "4.5.15", features = ["derive"] }

[dependencies.async-std]
features = ["attributes"]
version = "1.12.0"
