version: 2
jobs:
  build:
    working_directory: /go/src/github.com/graphite-ng/carbon-relay-ng
    docker:
      - image: circleci/golang:1.10.3
    steps:
      - checkout
      - run: go test -v -race $(go list ./... | grep -v /vendor/)
      - run: sudo apt-get install ruby-dev rpm
      - run: sudo gem install package_cloud
      - run: sudo gem install fpm
      - run: go get github.com/jteeuwen/go-bindata/...
      - run: make packages docker # note, this runs go-bindata again
      # ideally we'd make sure that if go-bindata generated new content, we fail.
      # because devs should have run go-bindata and checked in changes already.
      # but because git checkout will change the timestamps and mode, it'll generate slight differences, and it's hard to filter those out
      # so for now, we just let it slip and assume devs will do a good enough job maintaining the generated data
      # - git diff --exit-code
      - run: make build-win
      - store_artifacts:
          path: build
      - store_artifacts:
          path: carbon-relay-ng.exe
  deploy:
    docker:
      - image: circleci/golang:1.10.3
    steps:
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               # Ubuntu 14.04 (trusty), 16.04 (xenial), debian 8 (jessie), debian 9 (stretch), debian 10 (buster, testing) Centos6 and Centos7.
               # (no debian 7 wheezy because that's sysvinit which we don't have packages for)
               package_cloud push ${PACKAGECLOUD_REPO}/ubuntu/trusty build/deb-upstart/carbon-relay-ng-*.deb
               package_cloud push ${PACKAGECLOUD_REPO}/ubuntu/xenial build/deb-systemd/carbon-relay-ng-*.deb
               package_cloud push ${PACKAGECLOUD_REPO}/debian/jessie build/deb-systemd/carbon-relay-ng-*.deb
               package_cloud push ${PACKAGECLOUD_REPO}/debian/stretch build/deb-systemd/carbon-relay-ng-*.deb
               package_cloud push ${PACKAGECLOUD_REPO}/debian/buster build/deb-systemd/carbon-relay-ng-*.deb
               package_cloud push ${PACKAGECLOUD_REPO}/el/6          build/centos-6/carbon-relay-ng-*.el6.*.rpm
               package_cloud push ${PACKAGECLOUD_REPO}/el/7          build/centos-7/carbon-relay-ng-*.el7.*.rpm
               docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_KEY
               ./deploy-docker.sh
            fi
