version: 2
defaults:
  taggedReleasesFilter: &taggedReleasesFilter
    tags:
      only: /^\d+\.\d+\.\d+((a|b|rc)\d)?$/ # matches 1.2.3, 1.2.3a1, 1.2.3b1, 1.2.3rc1 etc..
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: pip install --user .
      - run: sudo pip install pylint==1.9.3 flake8 mock==3.0.5
      - run: make test
      - store_artifacts:
          path: pylint.out
      - store_artifacts:
          path: flake8.out

  snyk:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: pip install dephell
      - run: dephell deps convert --from=setup.py --to=requirements.txt
      - run: curl -sL https://raw.githubusercontent.com/segmentio/snyk_helpers/master/initialization/snyk.sh | sh

  test_27: &test
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: pip install --user .[test]
      - run:
          name: Linting with Flake8
          command: |
            git diff origin/master..HEAD analytics | flake8 --diff --max-complexity=10 analytics
      - run: make test
      - run: make e2e_test
  
  test_35:
    <<: *test
    docker:
      - image: circleci/python:3.5

  test_36:
    <<: *test
    docker:
      - image: circleci/python:3.6

  test_37:
    <<: *test
    docker:
      - image: circleci/python:3.7

  test_38:
    <<: *test
    docker:
      - image: circleci/python:3.8

  test_39:
    <<: *test
    docker:
      - image: circleci/python:3.9

  publish:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo pip install twine
      - run: make release

workflows:
  version: 2
  build_test_release:
    jobs:
      - build:
          filters:
            <<: *taggedReleasesFilter
      - test_27:
          filters:
            <<: *taggedReleasesFilter
      - test_35:
          filters:
            <<: *taggedReleasesFilter
      - test_36:
          filters:
            <<: *taggedReleasesFilter
      - test_37:
          filters:
            <<: *taggedReleasesFilter
      - test_38:
          filters:
            <<: *taggedReleasesFilter
      - test_39:
          filters:
            <<: *taggedReleasesFilter
      - publish:
          requires:
            - build
            - test_27
            - test_35
            - test_36
            - test_37
            - test_38
            - test_39
          filters:
            <<: *taggedReleasesFilter
            branches:
              ignore: /.*/
  static_analysis:
    jobs:
      - build
      - snyk:
          context: snyk
          requires:
            - build
  scheduled_e2e_test:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
                - scheduled_e2e_testing
    jobs:
      - test_27
      - test_35
      - test_36
      - test_37
      - test_38
      - test_39
