extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680

processors:
  batch:
    timeout: 30s
  queued_retry:

exporters:
  logging:
    loglevel: debug
  awsxray:
    local_mode: true
    region: 'us-west-2'
  awsemf:
    local_mode: true
    region: 'us-west-2'

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray, logging]
    metrics:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [awsemf, logging]

  extensions: [health_check]
