#on: [push]
on:
 workflow_dispatch:
 
jobs:
  build-framework:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build xcframework
        run: |
            ./scripts/prep_xcframework.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release_framework
          path: |
            ./Branch.zip
  build-testbed:
    runs-on: macos-latest
    needs: [build-framework]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: BranchMetrics/qentelli-saas-sdk-testing-ios-testbed
          token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
      - name: Download build artifacts
        uses: actions/download-artifact@v3
      - name : Unzip and copy folder
        run: |
            ls -la release_framework/
            ls -la release_framework/Branch.zip
            unzip release_framework/Branch.zip - d ./Framework
            ls -la ./Framework
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
          owner: BranchMetrics
          repo: qentelli-saas-sdk-testing-automation
          github_token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
          workflow_file_name: ios-maven.yml
          ref: 'test-trigger-from-iOSSDKRepo'
          wait_interval: 10
          client_payload: '{}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
    - name: Fetching test report from automation suite
      uses: dawidd6/action-download-artifact@v2
      with:
       github_token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
       repo: BranchMetrics/qentelli-saas-sdk-testing-automation
       workflow: ios-maven.yml
       branch: development
       name: test-results
       check_artifacts:  true
       search_artifacts:  true
       skip_unpack: false
       
    - name: Display S3 url
#       run: grep -C2 'Test report file link' output.txt
      run: grep 'Test report file link' output.txt
    
#     - name: Publishing test report to artifact
#       uses: actions/upload-artifact@v3
#       with:
#         name: test-results
#         path: ./*
        
        
