#on: [push]
on:
 workflow_dispatch:
 
jobs:
  build-framework:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build xcframework
        run: |
            ./scripts/prep_static_xcframework.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release_framework
          path: |
            ./Branch_static.zip
  build-testbed:
    runs-on: macos-latest
    needs: [build-framework]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: BranchMetrics/qentelli-saas-sdk-testing-ios-testbed
          ref: test-dynamic-linking
          token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision

          # import certificate 
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          
      - name: Download build artifacts
        uses: actions/download-artifact@v3
      - name : Unzip and copy folder
        run: |
            ls -la ./
            echo pwd
            ls -la release_framework/
            ls -la release_framework/Branch_static.zip
            unzip release_framework/Branch_static.zip -d ./Framework/
            ls -la ./Framework
            xcodebuild -workspace DeepLinkDemo.xcworkspace -scheme DeepLinkDemo  -sdk iphoneos archive -archivePath ./IPA/DeepLinkDemo.xcarchive
            # xcodebuild -workspace DeepLinkDemo.xcworkspace -scheme DeepLinkDemo  -sdk iphoneos -allowProvisioningUpdates archive -archivePath ./IPA/DeepLinkDemo.xcarchive
            ls -la ./IPA/
            xcodebuild -exportArchive -archivePath ./IPA/DeepLinkDemo.xcarchive -exportOptionsPlist IPA/Info.plist -exportPath IPA/
            ls -la ./IPA/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DeepLinkDemo.ipa
          path: |
                ./IPA/DeepLinkDemo.ipa
  buildAutomationTestSuite:
    runs-on: macos-latest
    needs: [build-testbed]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: BranchMetrics/qentelli-saas-sdk-testing-automation
          token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name : Unzip and copy folder
        run: |
            ls -la ./
            cp -R DeepLinkDemo.ipa testdata/builds/iOS_TestbedApp_21-Jun-2022-1.ipa
      - name: Build with Maven
        # run: mvn -B package --file pom.xml
        id: build_maven
        run: |
          # mvn clean
          # mvn -B clean install package -DskipTests
           mvn clean test -DsuiteXMLFile=testng.xml -e -DInputFormat="json" -DInputFilePath="TestSelection_BrowserStack_iOS.json" -DAccessKey="${{ secrets.S3_ACCESS_KEY }}" -DSecretKey="${{ secrets.S3_SECRET_KEY }}" --log-file output.txt
         
      - name: Print output
        if: always()        # run this step even if previous step failed
        run: cat ${{ github.workspace }}/output.txt
          
      - name: Publishing test report
        if: always()        # run this step even if previous step failed
        uses: actions/upload-artifact@v3  # upload test results
        with:
          name: test-results
          path: ${{ github.workspace }}/output.txt

  build:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
          owner: BranchMetrics
          repo: qentelli-saas-sdk-testing-automation
          github_token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
          workflow_file_name: ios-maven.yml
          ref: 'test-trigger-from-iOSSDKRepo'
          wait_interval: 10
          client_payload: '{}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
    - name: Fetching test report from automation suite
      uses: dawidd6/action-download-artifact@v2
      with:
       github_token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
       repo: BranchMetrics/qentelli-saas-sdk-testing-automation
       workflow: ios-maven.yml
       branch: development
       name: test-results
       check_artifacts:  true
       search_artifacts:  true
       skip_unpack: false
       
    - name: Display S3 url
#       run: grep -C2 'Test report file link' output.txt
      run: grep 'Test report file link' output.txt
    
#     - name: Publishing test report to artifact
#       uses: actions/upload-artifact@v3
#       with:
#         name: test-results
#         path: ./*
        
        
