name: Publish beta release when pushing to the main branch

on:
  push:
    branches: [main]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm ci
      - run: npm run build

      # Note, that the angular library needs to be built again to update the package.json in
      # 'libraries/ui-library-angular/dist/ui-library-angular/package.json'.
      - name: bump version to next beta release
        run: |
          npm version prerelease -w libraries --no-git-tag-version
          npm run build -w libraries/ui-library-angular

      - name: publish
        run: |
          npm publish libraries/ui-library/
          npm publish libraries/ui-library-react/
          npm publish libraries/ui-library-vue/
          npm publish libraries/ui-library-angular/dist/ui-library-angular/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
