name: Merge Dependabot PRs
on:
  schedule:
    - cron: '0 9 * * 1'  # Run this workflow every Monday at 9:00
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.DEPENDABOT_MERGER_PAT }}" | gh auth login --with-token

      - name: Ensure test branch is up to date with master
        run: |
          git config --global user.email "dependabot-merger-bot@branch.io"
          git config --global user.name "Dependabot Merger Bot"
          git checkout master
          git pull
          git checkout dependabot-test-branch
          git merge master || echo "Failed to merge master into test branch."

      - name: Get list of PRs from dependabot
        id: pr_list
        run: |
          PR_LIST=$(gh pr list --json number,headRefName --jq '.[] | "\(.number) \(.headRefName)"' | grep dependabot)
          echo "::set-output name=numbers::$PR_LIST"
          echo "PRs to be merged: $PR_LIST"
      
      - name: Merge PRs into test branch
        run: |
          git checkout dependabot-test-branch
          echo "${{ steps.pr_list.outputs.numbers }}" | while IFS=' ' read -r PR_NUMBER BRANCH_NAME
          do
            echo "Merging PR #$PR_NUMBER from branch $BRANCH_NAME into test branch..."
            git fetch origin $BRANCH_NAME
            git merge --no-commit --strategy-option theirs origin/$BRANCH_NAME
            echo "Pushing changes to dependabot-test-branch..."
            git commit -m "Merged PR #$PR_NUMBER into test branch"
            git push origin dependabot-test-branch
          done
