name: Merge Dependabot PRs
on:
  schedule:
    - cron: '0 9 * * 1'  # Run this workflow every Monday at 9:00
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.DEPENDABOT_MERGER_PAT }}" | gh auth login --with-token

      - name: Ensure test branch is up to date with master
        run: |
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git checkout master
          git pull
          git checkout dependabot-test-branch
          git merge master --allow-unrelated-histories

      - name: Get list of PRs from dependabot
        id: pr_list
        run: |
          echo "::set-output name=numbers::$(gh pr list | grep dependabot | awk '{print $1}')"

      - name: Merge PRs into test branch
        run: |
          IFS=' ' read -r -a array <<< "${{ steps.pr_list.outputs.numbers }}"
          for PR_NUMBER in "${array[@]}"
          do
            gh pr checkout $PR_NUMBER
            git merge --no-ff -m "Merging PR #$PR_NUMBER via GitHub Action"
            git push origin dependabot-test-branch
          done
