name: Post Release SDK Integration Tests

on: [workflow_dispatch,push]

jobs:
  verify-cocoapods-iOS:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install pod, build project and run tests
        run: |
            cd  SDKIntegrationTestApps/PostRelease-iOSReleaseTest-Cocoapods/
            pod install
            xcodebuild test -scheme iOSReleaseTest -workspace iOSReleaseTest.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest' | xcpretty && exit ${PIPESTATUS[0]}
  verify-carthage-iOS:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run carthage command, build project and run tests
        run: |
            cd  SDKIntegrationTestApps/PostRelease-iOSReleaseTest-Carthage/
            carthage update --use-xcframeworks
            xcodebuild test -scheme iOSReleaseTest -project iOSReleaseTest.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest' | xcpretty && exit ${PIPESTATUS[0]}
  verify-SPM-iOS:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: build project and run tests
        run: |
            cd  SDKIntegrationTestApps/PostRelease-iOSReleaseTest-SPM/
            xcodebuild test -scheme iOSReleaseTest -project iOSReleaseTest.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest' | xcpretty && exit ${PIPESTATUS[0]}
  verify-cocoapods-tvOS:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install pod, build project and run tests
        run: |
            cd  SDKIntegrationTestApps/PostRelease-tvOSReleaseTest-Cocoapods/
            pod install
            xcodebuild test -scheme tvOSReleaseTest -workspace tvOSReleaseTest.xcworkspace -destination 'platform=tvOS Simulator,name=Apple TV,OS=latest' | xcpretty && exit ${PIPESTATUS[0]}

