name: sync modules repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dateutil requests 

    - name: sync data
      run: python ./util/cli.py sync

    - name: push 
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update modules repo 
