name: Run unit tests

# For testing
on:
  push

# on:
#   pull_request:
#     branches:
#       - master

jobs:
  verify:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            vendor
            Branch-TestBed/Pods
          key: ${{ runner.os }}-${{ hashFiles('Gemfile.lock','Branch-TestBed/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install Ruby dependencies
        run: |
          bundle config set --local path vendor
          bundle check || bundle install
      - name: Run unit tests
        run: bundle exec fastlane unit_tests
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always() # even if tests fail
        with:
          name: test-results
          path: fastlane/test_output
